### ISSUE TITLE
Error Docker run 

### ISSUE THREAD

**Issue by carlosalejandromiranda** [szaffarano/panama#2]
Cuando se ejecuta el comando siguiente : 
# sudo docker exec -it docker_neo_1 bin/neo4j-shell -file import/create.cypher

Error response from daemon: No such container: docker_neo_1

El nombre del contendor no es docker_neo_1 , por ejemplo :
# sudo docker ps

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                      NAMES
7e55f289bc1c        neo4j:3.0           "/docker-entrypoint.s"   27 seconds ago      Up 26 seconds       0.0.0.0:7474->7474/tcp, 7473/tcp, 0.0.0.0:7687->7687/tcp   panama_neo_1

**Comment by szaffarano** [comment]
Es verdad, depende del nombre del directorio que contiene al proyecto.  En mi ambiente tengo todo en una carpeta "docker", que es el prefijo del nombre del contenedor, en la tuya seguramente es "panama".  Hay que agregar un script para independizarse de estas cuestiones.

**Comment by szaffarano** [comment]
Resuelto en commit eee0f4527b648515b3e234e1bf1d4ee778912539
